config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :product_search do
    get :search, on: :collection
  end
  resources :product_details, only: %i{show}
  resources :dashboard, only: %i{index}
  namespace :dashboard do
    resources :groups, except: %i{show destroy}
    resources :families, except: %i{show destroy}
    resources :tax_classifications, except: %i{show destroy}
    resources :products, except: %i{show} 
    resources :lines, except: %i{show destroy}
  end
end

app/models/group.rb
class Group < ApplicationRecord
  validates :group_code, :group_description, presence: true
  validates :group_code, :group_description, uniqueness: true

  has_many :families, dependent: :destroy
end

app/controllers/dashboard/families_controller.rb
class Dashboard::FamiliesController < DashboardController
  layout 'dashboard'
  before_action :set_families, only: %i[edit update]

  def index
    @families = Family.all
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(families_params)
    if @family.save
      redirect_to dashboard_families_path, notice: "#{@family.family_description} cadastrada com sucesso!"
    else
      flash.now[:alert] = @family.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @family.update(families_params)
      redirect_to dashboard_families_path, notice: "#{@family.family_description} atualizada com sucesso!" 
    else
      flash.now[:alert] = @family.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_families
    @family = Family.find(params[:id])
  end

  def families_params
    params.require(:family).permit(:family_code, :family_description, :group_id)
  end
end

app/controllers/dashboard/groups_controller.rb
class Dashboard::GroupsController < DashboardController
  layout 'dashboard'
  before_action :set_groups, only: %i[edit update]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to dashboard_groups_path, notice: "#{@group.group_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @group.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to dashboard_groups_path, notice: "#{@group.group_description} atualizado com sucesso!" 
    else
      flash.now[:alert] = @group.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_groups
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:group_code, :group_description)
  end
end

app/controllers/dashboard/lines_controller.rb
class Dashboard::LinesController < DashboardController

  before_action :line, only: %i[edit update]

  def index
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new(lines_params)
    if @line.save
      redirect_to dashboard_lines_path, notice: "#{@line.group_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @line.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @line.update
      redirect_to dashboard_lines_path, notice: "#{@line.group_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @line.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def set_lines
    @line = Line.find(params[:id])
  end

  def lines_params
    params.require(:line).permit(:line_description)
  end


end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < DashboardController
  layout 'dashboard'
  before_action :set_products, only: %i[edit update]
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to dashboard_products_path, notice: "#{@product.product_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(products_params)
      redirect_to dashboard_products_path, notice: "#{@product.product_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :edit
    end
  end


  private


  def set_products
    @product = Product.friendly.find(params[:id])
  end

  def products_params
    params.require(:product).permit(:product_code, :product_description, :product_ean, :product_dun, :display_ean, :status,
     :releases, :family_id, :tax_classification_id, :group_id, :generic_id, :image)
  end
end

app/controllers/dashboard/tax_classifications_controller.rb
class Dashboard::TaxClassificationsController < DashboardController
  layout 'dashboard'
  before_action :set_tax_classification, only: %i[edit update]
  
  def index
    @tax_classifications = TaxClassification.all
  end

  def new
    @tax_classification = TaxClassification.new
  end

  def create
    @tax_classification = TaxClassification.new(tax_classifications_params)
    if @tax_classification.save
      redirect_to dashboard_tax_classifications_path, notice: "Classificação cadastrada com sucesso!"
    else
      flash.now[:alert] = @tax_classification.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit    
  end

  def update
    if @tax_classification.update(tax_classifications_params)
      redirect_to dashboard_tax_classifications_path, notice: "Classificação alterada com sucesso!"
    else
      flash.now[:alert] = @tax_classification.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_tax_classification
    @tax_classification = TaxClassification.find(params[:id])
  end

  def tax_classifications_params
    params.require(:tax_classification).permit(:tax_code)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "dashboard"

  def index
    @products = Product.all.count
    @products_releases = Product.releases_true
    @products_status = Product.status_true
  end
end

app/views/dashboard/groups/_form_group.html.erb
<%= form_with model: [:dashboard, @group], local: true do |f| %>
  <div class="row mb-3 offset-md-2">
    <div class="form-group col-md-5">
      <%= f.label :group_code, 'Código do Grupo' %>
      <%= f.text_field :group_code, class: "form-control" %>
    </div>
    <div class="form-group col-md-5">
      <%= f.label :group_description, 'Descrição do Grupo' %>
      <%= f.text_field :group_description, class: "form-control" %>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit class: 'btn btn-success', data: { disable_with: 'Criando....⌛'} %>
    <%= link_to 'Cancelar', dashboard_groups_path, class: "btn btn-danger ml-1" %>
  </div>
<% end %>

app/views/dashboard/groups/edit.html.erb
<div class="container-fluid">
  <h1 class="h3 mb-4 text-gray-800">Editando grupo</h1>
  <%= render 'form_group' %>
</div>

app/views/dashboard/groups/index.html.erb
<div class="container-fluid">
  <h1 class="h3 mb-4 text-gray-800">Grupos de produtos</h1>
  <%= link_to 'Cadastrar', new_dashboard_group_path, class:"btn btn-success mb-2" %>
  <% if @groups.empty? %>
    <div class="alert alert-danger" role="alert">
      Nenhum grupo cadastrado!
    </div>
  <% else %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Código Grupo</th>
          <th scope="col">Descrição Grupo</th>
          <th scope="col">Alterar</th>
        </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <th scope="row"><%= group.id %></th>
            <td><%= group.group_code %></td>
            <td><%= group.group_description %></td>
            <td><%= link_to 'Editar', edit_dashboard_group_path(group), class:"btn btn-secondary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/dashboard/groups/new.html.erb
<div class="container-fluid">
  <h1 class="h3 mb-4 text-gray-800">Cadastando grupo</h1>
  <%= render 'form_group' %>
</div>