config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :product_search do
    get :search, on: :collection
  end
  resources :product_details, only: %i{show}
  resources :dashboard, only: %i{index}
  namespace :dashboard do
    resources :groups, except: %i{show destroy}
    resources :families, except: %i{show destroy}
    resources :tax_classifications, except: %i{show destroy}
    resources :products, except: %i{show} 
    resources :lines, except: %i{show destroy}
  end
end

app/views/layouts/shared_dashboard/_footer.html.erb
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span class="footer-new">Copyright &copy; Catálogo Nestlé <%= Date.current.year %> - <a class="link" href="https://br.linkedin.com/in/fabriciobonjorno" target="_blank">Feito por: Fabricio Bonjorno</a>.</span>
          </div>
        </div>
      </footer>

app/views/layouts/shared_dashboard/_nav.html.erb
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>
            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>

app/views/layouts/shared_dashboard/_sidebar.html.erb
    
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <!-- Sidebar - Brand -->
    <div class="sidebar-brand-text mx-3"><%= link_to 'Catalogo Nestlé', dashboard_index_path, class:"sidebar-brand d-flex align-items-center justify-content-center" %></div>
  <!-- Divider -->
  <hr class="sidebar-divider my-0">
  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <span> <%= link_to 'Grupos', dashboard_groups_path, class: "nav-link collapsed" %></span>
  </li>
  <li class="nav-item">
    <span> <%= link_to 'Familias', dashboard_families_path, class: "nav-link collapsed" %></span>
  </li>
  <li class="nav-item">
    <span> <%= link_to 'Classificações', dashboard_tax_classifications_path, class: "nav-link collapsed" %></span>
  </li>
  <li class="nav-item">
    <span> <%= link_to 'Produtos', dashboard_products_path, class: "nav-link collapsed" %></span>
  </li>
</ul>