config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :product_search do
    get :search, on: :collection
  end
  resources :product_details, only: %i{show}
  resources :dashboard, only: %i{index}
  namespace :dashboard do
    resources :groups, except: %i{show destroy}
    resources :families, except: %i{show destroy}
    resources :tax_classifications, except: %i{show destroy}
    resources :products, except: %i{show} 
    resources :lines, except: %i{show destroy}
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include PgSearch
  extend FriendlyId
  validates :product_code, :product_description, :product_ean, :product_dun, presence: true
  validates :product_code, :product_description, :product_ean, :product_dun, uniqueness: true

  belongs_to :family
  belongs_to :group
  belongs_to :tax_classification
  belongs_to :line

  has_many :generics, class_name: 'Product', foreign_key: 'generic_id'
  belongs_to :generic, class_name: 'Product', optional: true

  has_one_attached :image

  friendly_id :product_description, use: :slugged

  pg_search_scope :search,
                  against: %i[product_description product_ean product_code product_dun]

  validate :image_validation

  def image_validation
    if respond_to?(:image) && image.attached?
      if image.blob.byte_size > 2_000_000
        image.purge
        errors[:base] << 'Tamanho maximo 2MB'
      elsif !image.blob.content_type.starts_with?('image/png', 'image/jpeg', 'image/jpg')
        image.purge
        errors[:base] << 'Formato invalido use PNG, JPEG, JPG'
      end
    end
  end

  scope :releases_home, -> { where(releases: true) }
  scope :releases_true, -> { where(releases: true).count }
  scope :status_true, -> { where(status: true).count }
end

app/controllers/dashboard/families_controller.rb
class Dashboard::FamiliesController < DashboardController
  layout 'dashboard'
  before_action :set_families, only: %i[edit update]

  def index
    @families = Family.all
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(families_params)
    if @family.save
      redirect_to dashboard_families_path, notice: "#{@family.family_description} cadastrada com sucesso!"
    else
      flash.now[:alert] = @family.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @family.update(families_params)
      redirect_to dashboard_families_path, notice: "#{@family.family_description} atualizada com sucesso!" 
    else
      flash.now[:alert] = @family.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_families
    @family = Family.find(params[:id])
  end

  def families_params
    params.require(:family).permit(:family_code, :family_description, :group_id)
  end
end

app/controllers/dashboard/groups_controller.rb
class Dashboard::GroupsController < DashboardController
  layout 'dashboard'
  before_action :set_groups, only: %i[edit update]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to dashboard_groups_path, notice: "#{@group.group_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @group.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to dashboard_groups_path, notice: "#{@group.group_description} atualizado com sucesso!" 
    else
      flash.now[:alert] = @group.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_groups
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:group_code, :group_description)
  end
end

app/controllers/dashboard/lines_controller.rb
class Dashboard::LinesController < DashboardController

  before_action :line, only: %i[edit update]

  def index
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new(lines_params)
    if @line.save
      redirect_to dashboard_lines_path, notice: "#{@line.group_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @line.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @line.update
      redirect_to dashboard_lines_path, notice: "#{@line.group_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @line.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def set_lines
    @line = Line.find(params[:id])
  end

  def lines_params
    params.require(:line).permit(:line_description)
  end


end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < DashboardController
  layout 'dashboard'
  before_action :set_products, only: %i[edit update]
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to dashboard_products_path, notice: "#{@product.product_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(products_params)
      redirect_to dashboard_products_path, notice: "#{@product.product_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :edit
    end
  end


  private


  def set_products
    @product = Product.friendly.find(params[:id])
  end

  def products_params
    params.require(:product).permit(:product_code, :product_description, :product_ean, :product_dun, :display_ean, :status,
     :releases, :family_id, :tax_classification_id, :group_id, :generic_id, :image)
  end
end

app/controllers/dashboard/tax_classifications_controller.rb
class Dashboard::TaxClassificationsController < DashboardController
  layout 'dashboard'
  before_action :set_tax_classification, only: %i[edit update]
  
  def index
    @tax_classifications = TaxClassification.all
  end

  def new
    @tax_classification = TaxClassification.new
  end

  def create
    @tax_classification = TaxClassification.new(tax_classifications_params)
    if @tax_classification.save
      redirect_to dashboard_tax_classifications_path, notice: "Classificação cadastrada com sucesso!"
    else
      flash.now[:alert] = @tax_classification.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit    
  end

  def update
    if @tax_classification.update(tax_classifications_params)
      redirect_to dashboard_tax_classifications_path, notice: "Classificação alterada com sucesso!"
    else
      flash.now[:alert] = @tax_classification.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_tax_classification
    @tax_classification = TaxClassification.find(params[:id])
  end

  def tax_classifications_params
    params.require(:tax_classification).permit(:tax_code)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "dashboard"

  def index
    @products = Product.all.count
    @products_releases = Product.releases_true
    @products_status = Product.status_true
  end
end

app/views/dashboard/products/_form_product.html.erb
<%= form_with(model: [:dashboard, @product], local: true, multipart: true) do |f| %>
  <div class="row">
    <div class="form-group col-md-2">
    <label>Grupo</label>
      <%= collection_select(:product, :group_id, Group.all, :id, :group_description, prompt: "Selecione", class:"form-control") %>
    </div>
    <div class="form-group col-md-2">
      <label>Familia</label>
      <%= collection_select(:product, :family_id, Family.all, :id, :family_description, prompt: "Selecione", class:"form-control") %>
    </div>
    <div class="form-group col-md-2">
      <label>Classificação</label>
      <%= collection_select(:product, :tax_classification_id, TaxClassification.all, :id, :tax_code, prompt: "Selecione", class:"form-control") %>
    </div>
        <div class="form-group col-md-2">
      <%= f.label :product_code, 'Código do Produto' %>
      <%= f.text_field :product_code, class: "form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :product_description, 'Descrição do produto' %>
      <%= f.text_field :product_description, class: "form-control" %>
    </div>
  </div>
  <div class="row mt-2">
      <div class="form-group col-md-2">
      <%= f.label :product_ean, 'Código Ean' %>
      <%= f.text_field :product_ean, class: "form-control" %>
    </div>
          <div class="form-group col-md-2">
      <%= f.label :display_ean, 'Ean Display' %>
      <%= f.text_field :display_ean, class: "form-control" %>
    </div>
          <div class="form-group col-md-2">
      <%= f.label :product_dun, 'Código Dun' %>
      <%= f.text_field :product_dun, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :generic_id, 'Produto Principal' %>
      <%= f.collection_select :generic_id, Product.all, :id, :product_description, {prompt: 'Selecione'} %>
    </div>
        <div class="form-group col-md-3">
      <%= f.label :image, 'Imagem' %>
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="row">
        <div class="form-group ml-2">
      <%= f.label :status, 'Ativo' %>
      <%= f.check_box :status, class: "custom-checkbox" %>
    </div>
    <div class="form-group ml-3">
      <%= f.label :releases, 'Lançamento' %>
      <%= f.check_box :releases, class: "custom-checkbox" %>
    </div>
  </div>

    <div class="text-center">

    <%= f.submit class: 'btn btn-success', data: { disable_with: 'Criando....⌛'} %>
    <%= link_to 'Cancelar', dashboard_products_path, class: "btn btn-danger ml-1" %>
  </div>
<% end %>

app/views/dashboard/products/bkp.hml.erb
            <td>
            <% if product.generics.present? %>
              <% product.generics.each do |generic| %>
                <%= generic.product_description %>
              <% end %>
            <% end %>
            </td>

app/views/dashboard/products/edit.html.erb
<div class="container-fluid">
  <h1 class="h3 mb-4 text-gray-800">Editando produto</h1>
  <%= render 'form_product' %>
</div>

app/views/dashboard/products/index.html.erb
<div class="container-fluid">
  <h1 class="h3 mb-4 text-gray-800">Lista de produtos</h1>
  <%= link_to 'Cadastrar', new_dashboard_product_path, class:"btn btn-success mb-2" %>
  <% if @products.empty? %>
    <div class="alert alert-danger" role="alert">
      Nenhum produto cadastrado!
    </div>
  <% else %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Descrição grupo</th>
          <th scope="col">Descrição familia</th>
          <th scope="col">Código produto</th>
          <th scope="col">Descrição produto</th>
          <th scope="col">Alterar</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <th scope="row"><%= product.id %></th>
            <td><%= product.group.group_description %></td>
            <td><%= product.family.family_description %></td>
            <td><%= product.product_code %></td>
            <td><%= product.product_description %></td>
            <td><%= link_to 'Editar', edit_dashboard_product_path(product), class:"btn btn-secondary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/dashboard/products/new.html.erb
<div class="container-fluid">
  <h1 class="h3 mb-4 text-gray-800">Cadastrando produto</h1>
  <%= render 'form_product' %>
</div>